#!/usr/bin/env escript
%% -*- erlang -*-

main([]) ->
	code:add_pathz("deps/protobuffs/ebin/"),
	Options = [{output_src_dir,"apps/roboss/src"},{output_include_dir,"apps/roboss/include"}],
	protobuffs_compile:generate_source("../protos/roboss.proto",Options),

	Options2 = [{output_src_dir,"apps/client/src"},{output_include_dir,"apps/client/include"}],
	protobuffs_compile:generate_source("../protos/client.proto",Options2);


main ([File]) ->
code:add_pathz("deps/protobuffs/ebin/"),
protobuffs_compile:generate_source (File).
