#!/usr/bin/env escript
%% -*- erlang -*-

main([]) ->
	code:add_pathz("deps/protobuffs/ebin/"),
	Options = [{output_src_dir,"src"},{output_include_dir,"include"}],
	protobuffs_compile:generate_source("../protos/roboss.proto",Options);

main ([File]) ->
code:add_pathz("deps/protobuffs/ebin/"),
protobuffs_compile:generate_source (File).
